[path]
# 数据库地址
dbPath="data/data.db"

[input]
# 输入模式: "text" (文本输入) 或 "audio" (语音输入)
mode = "audio"
# 是否为半双工对话，默认回声消除由硬件侧处理，如果硬件侧没有处理则参考 tests/ace.py 改写相关代码，如果都不处理则将改值置为 False
half_duplex_communication = "True"

[output]
# 输出模式: "text" (文本输出) 或 "audio" (语音输出)
mode = "audio"

[speaker]
# 朗读模型地址
model = "models/Qwen3-TTS-12Hz-0.6B-CustomVoice"

[audio]
# 语音识别模型大小
model = "models/faster-whisper-large-v3-turbo"
# VAD
vad = "models/silero-vad"
# 语言
language = "zh"
# 采样率（Hz）
sample_rate = 16000
# 每个音频块的时长（秒）
chunk_duration = 0.1
# 停顿多久算一句结束（毫秒）
min_silence_ms = 1000
# 最短语音长度（毫秒）
min_audio_ms = 500
# VAD检测窗口大小（秒）
vad_window_sec = 0.8


[service]
# 向量库地址
qdrant_url = "http://localhost:6333"
# Ollama地址
ollama_base_url = "http://localhost:11434"
# Redis地址
redis_url = "redis://localhost:6379"
# 主LLM模型
llm_model = "qwen3:14b-q4_K_M"
# 辅助LLM模型
llm_model_light = "qwen2.5:1.5b"
# Embedding模型
embed_text_model = "bge-m3"
# 每次启动删除清空向量库
reset_collections = "True"
