[project]
name = "meow-ai-agent"
version = "0.1.0"
description = ""
authors = [
    { name = "AsterCasc", email = "astercass@qq.com" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    # 一般
    #"flask>=3.1.2", # HTTP 服务端
    #"httpx>=0.28.1", # Http 客户端
    "loguru>=0.7.3", # 日志
    #"polars>=1.38.1", # 数据处理
    #"pydantic>=2.12.5", # Json 序列化/反序列化
    "python-dotenv>=1.2.2", # 加载环境变量
    #"redis>=7.1.0", # Redis
    #"rich>=14.3.2", # 终端渲染
    #"pyside6>=6.10.2", # UI
    # 额外
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.25",
    "langchain-ollama>=1.0.1",
    "llama-index>=0.14.19",
    "langchain>=1.2.14",
    "ddgs>=9.12.0",
    "langgraph-checkpoint-sqlite>=3.0.3",
    "langchain-qdrant>=1.1.0",
    "rank-bm25>=0.2.2",
    "jieba>=0.42.1",
    "pypdf>=6.9.2",
    "python-docx>=1.2.0",
    "docx2txt>=0.9",
]

[[tool.uv.index]]
name = "tuna"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[[tool.uv.index]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"

[dependency-groups]
dev = [
    "hatchling>=1.29.0", # 构建引擎
    "pyinstaller>=6.19.0", # 打包
    "pytest>=9.0.2", # 测试
    "pytest-cov>=7.0.0", # 测试代码覆盖
    "ruff>=0.15.5", # 代码格式化
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
app = "meow_ai_agent.__main__:main"
